# For development
version: '3'
services:
  backend:
    container_name: ibuki-backend
    build:
      context: backend
    ports:
      - '3001:3001'
    volumes:
      - type: bind
        source: './backend'
        target: '/backend'
      - type: bind
        source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
    command: 'npm run start:debug'

  frontend:
    container_name: ibuki-frontend
    build:
      context: frontend
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: './frontend'
        target: '/frontend'
    command: 'npm run dev'
