# For development
version: '3'
services:
  backend:
    container_name: ibuki-backend
    build:
      context: backend
    ports:
      - '3001:3001'
    volumes:
      - './backend:/backend'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: 'npm run start:debug'

  frontend:
    container_name: ibuki-frontend
    build:
      context: frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/frontend'
    command: 'npm run dev'
