FROM node:14.16-buster-slim

 # for npm run start:debug
RUN apt-get update
RUN apt-get install -y procps

# RUN mkdir /project

# ADD package.json /project
# ADD package-lock.json /project

# WORKDIR /project

# RUN npm install


WORKDIR /backend
